version: '3.9'
services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "27017:27017"
    volumes:
      - node-mongo-data
  rest-api-app:
    depends_on:
      - mongodb
    build: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "3000:3000"
    environment:
      - NODE_PORT=$NODE_PORT
      - DB_HOST=$DB_HOST
      - DB_NAME=$DB_DATABASE
      - DB_PORT=$DB_PORT
    volumes:
      - ./api:/usr/src/app/api
volumes:
  node-mongo-data: